data_dir: "data/torch/joined"
batch_size: 128
img_size: [128, 128]
learning_rate: 0.0001
num_epochs: 100
early_stopping_patience: 10
model_save_path: "test"

model:
  name: small_vit
  params:
    pretrained_resnet:
      num_classes: 8
      pretrained: true
    small_cnn:
      num_classes: 8
    small_vit:
      num_classes: 8
      dropout: 0.05

optimizer:
  name: Adam
  params:
    lr: 0.0001
    weight_decay: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    StepLR:
      step_size: 10
      gamma: 0.1
    CosineAnnealingLR:
      T_max: 5
      eta_min: 0.000005
    OneCycleLR:
      max_lr: 0.0005
      total_steps: 100
      pct_start: 0.3
      anneal_strategy: 'cos'
      cycle_momentum: False

