name: Ruff Linting

on:
  pull_request:

jobs:
  lint:
    name: Ruff check with PEP8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: pip install ruff==0.11.2

      - name: Run Ruff linter and formatter
        run: ruff check . && ruff format --diff .
